"""add prompt_injection_suspected to request_logs

Revision ID: 5c2c60e19d28
Revises: 90d73b85b214
Create Date: 2026-08-25 21:27:10.265339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2c60e19d28'
down_revision: Union[str, Sequence[str], None] = '90d73b85b214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('prompt_injection_suspected', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'prompt_injection_suspected')
    # ### end Alembic commands ###
